### ISSUE TITLE
06-事件监听/03-v-on的修饰符 @keyup.enter监听键盘代码有误

### ISSUE THREAD

**Issue by xpangel** [zhangtianyi0110/VueLearnNotes#11]
第20行
`    <input type="text" @click.enter="keyup">`
应该是
`    <input type="text" @keyup.enter="keyup">`
     这个地方监听的是键盘输入而不是鼠标点击

**Comment by zhangtianyi0110** [comment]
感谢，已修改：https://github.com/zhangtianyi0110/VueLearnNotes/commit/5f198ce6116fe43503a45cfabaa8485b70bc6107
